---
- name: Verify that ansible can correctly pass arguments to ansible in shell
  hosts: localhost
  gather_facts: False
  # vars:  # fix option number 1
  #   ansible_remote_tmp: /runner/.ansible/tmp
  tasks:
    - name: Write inventory file
      blockinfile:
        path: '/runner/inventory.ansible.shell'
        block: |
          localhost ansible_connection=local
        state: present
        # unsafe_writes: true  # fix does not work
        create: True
