---
- hosts: localhost
  gather_facts: false
  connection: local
  name: Show bug with get_url module and runner
  # vars:  # fix option 1
  #   ansible_remote_tmp: /runner/.ansible/tmp
  tasks:

    - name: Get archive from url
      get_url:
        url: "https://github.com/ansible/ansible-builder/archive/0.3.1.zip/"
        dest: "/runner/ansible-builder.zip"
